### ISSUE TITLE
Manual Edit UI for Readme and Meta

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#273]
The manual dataset uploading UI is the same layout as the dataset editor.  Since that work is already in, let's modify this work to use those components.

**Add meta and readme editing to manual dataset creation flow**
- [ ] Make readme and meta tabs in the manual update screen editable

**Create a new `/edit` route with the same layout as the manual upload route**
- [ ] When the user clicks 'edit' in the history view, let's navigate to `/:username/:datasetname/edit` and show the same UI that we show for manual dataset creation, but with different state for editing the active dataset

- [ ] Confirm that the full editing flow works
  - [ ] Go to existing dataset history view
  - [ ] Click "edit"
  - [ ] Navigate to `/:username/:datasetname/edit`
  - [ ] Make a change to the readme and/or metadata
  - [ ] Make a change to the Title in the dataset header, it should also be reflected in the meta tab
  - [ ] Commit
  - [ ] Navigate back to `/history` showing the current version of the dataset
